import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useForm } from "react-hook-form";
import type { UseFormRegisterReturn } from "react-hook-form";

import firebase from "firebase/compat/app";
import { FirebaseApp, initializeApp } from "firebase/app";
import {
  Firestore,
  addDoc,
  getFirestore,
  collection,
  getDocs,
  DocumentReference,
  doc,
} from "firebase/firestore";
import "firebase/analytics";
import "firebase/auth";
import "firebase/firestore";

import moment from "moment";
import "moment/locale/ko";

import styles from "../styles/Home.module.css";
import NFStudioBannerImage from "public/Banner/NewFlare.png";
import { v4 as uuidv4 } from "uuid";
import { useEffect, useState } from "react";

interface IClass {
  instructorName: string;
  classTime: string;
  classID: string;
}

interface IEnrollment {
  name: string;
  phone: string;
}

interface ICoupon {
  title: string;
  value: number;
}

const Home: NextPage = () => {
  const coupons = [
    {
      title: "1class",
      value: 30_000,
    },
    {
      title: "2class",
      value: 55_000,
    },
    {
      title: "3class",
      value: 80_000,
    },
    {
      title: "4class",
      value: 100_000,
    },
    {
      title: "5class",
      value: 120_000,
    },
    {
      title: "8class",
      value: 180_000,
    },
    {
      title: "free pass",
      value: 400_000,
    },
  ];

  // Firebase
  const [newFlareCoupones, setCoupon] = useState<ICoupon[]>(coupons);
  const [enrollment, setEnrollment] = useState<IClass[]>([]);
  const datas: IClass[] = [];

  const firebaseConfig = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_APP_ID,
    measurementId: process.env.NEXT_PUBLIC_MERASUREMENT_ID,
  };

  const app = initializeApp(firebaseConfig);
  const db = getFirestore(app);

  useEffect(() => {
    // const classList = enrollment.map((v) => (
    //   // eslint-disable-next-line react/jsx-key
    //   <DanceClass
    //     key={v.classID}
    //     classTime={v.classTime}
    //     instructorName={v.instructorName}
    //   />
    // ));

    const NewFlareDanceClass = async (db: Firestore) => {
      const danceClasses = collection(db, "classes");
      const classSnapshot = await getDocs(danceClasses);
      const classList = classSnapshot.docs.map((doc) => doc.data());
      const NewFlareStudioClass = classList.filter(
        (aClass) => aClass.studioID === process.env.NEXT_PUBLIC_NF_STUDIO_ID
      );

      return NewFlareStudioClass;
    };

    NewFlareDanceClass(db).then((value) => {
      value.map((e) => {
        const numberParseDay = Number(moment(e.date.toDate()).format("DD"));
        const today = Number(moment().format("DD"));

        const { instructorName } = e;
        if (numberParseDay >= today && numberParseDay <= today + 7) {
          const classTime = moment(e.date.toDate()).format(
            "MM월 DD일 (ddd) HH:mm"
          );

          datas.push({ classID: e.ID, classTime, instructorName });
        }
      });

      let sortClass = datas.sort(
        (a, b) =>
          Number(a.classTime.split(" ")[1].replace("일", "")) -
          Number(b.classTime.split(" ")[1].replace("일", ""))
      );

      setEnrollment(sortClass);
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  //TODO: Register DanceClass에 상속
  const { register, handleSubmit } = useForm();

  return (
    <div className={styles.container}>
      <Head>
        <title>NewFlare Dance Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.header}>
          <h1> 10월 CLASS </h1>
          <div className={styles.imageContainer}>
            <Image
              src={NFStudioBannerImage}
              alt="NewFlare Studio Banner image"
              objectFit="cover"
              objectPosition="center"
            ></Image>
          </div>
        </section>
        <div className={styles.description}>
          <h2>Class Price</h2>
          <div>쿠폰 (사용 기간 1개월)</div>
          <>
            {newFlareCoupones.map((aCoupon) => (
              // eslint-disable-next-line react/jsx-key
              <div
                key={aCoupon.title}
              >{`${aCoupon.title} -> ${aCoupon.value}`}</div>
            ))}
          </>
          <div className={styles.subDescription}>
            <div>정규 수업신청시</div>
            <div>한 과목만 수강 한 달 4회 기준(1회 연장 사용 가능)</div>
            <div>100,000</div>
          </div>
        </div>
        <form
          className={styles.chooseClass}
          onSubmit={handleSubmit(async (data) => {
            const classeId = Object.keys(data)
              .splice(4)
              .filter((el) => data[el] === true)[0];

            try {
              const docRef = await addDoc(collection(db, "enrollment"), {
                ID: uuidv4(),
                enrolledDate: new Date(),
                classID: classeId,
                userName: data.name,
                phoneNumber: data.phone,
                number: 1,
                paid: false,
              });
              console.log("Document written with ID: ", docRef.id);
            } catch (error) {
              console.log(error);
            }

            alert(`${data.name}님  수강신청 완료했습니다 !!`);
          })}
          method="post"
        >
          <section className={styles.classSelectStudentInfo}>
            <h2>이름 (입금자명) </h2>
            <input
              type="text"
              id=""
              placeholder="ex. 김민수(김민수)"
              {...register("name")}
            />
          </section>
          <section className={styles.classSelectStudentInfo}>
            <h2>전화번호</h2>
            <input
              type="text"
              id=""
              placeholder="010-5094-6369"
              {...register("phone")}
            />
          </section>
          <section className={styles.classSelectStudentInfo}>
            <h2>수업신청 (날짜&강사명) 복수기제 가능</h2>
            <input
              type="text"
              id=""
              placeholder="콤마를 이용해 구분해주세요"
              {...register("classRequest")}
            />
          </section>
          <section className={styles.formField}>
            <h2>클래스 선택</h2>
            <>
              {enrollment.map((aClass) => (
                <>
                  <div className={styles.classSelectForm}>
                    <div className={styles.classSelectCheckBox}>
                      <label className={styles.checkBoxContainer}>
                        <input type="checkbox" {...register(aClass.classID)} />
                        <span className={styles.checkmark}></span>
                      </label>
                      <span>{aClass.classTime}</span>
                    </div>
                    <div className={styles.formDetail}>
                      {aClass.instructorName}
                    </div>
                  </div>
                </>
              ))}
            </>
          </section>

          <section className={styles.formField}>
            <div className={styles.chooseClass}>
              <h2>쿠폰</h2>
              <div className={styles.classSelectForm}>
                <div className={styles.classSelectCheckBox}>
                  <label className={styles.checkBoxContainer}>
                    <input type="checkbox" {...register("ticket1")} />
                    <span className={styles.checkmark}></span>
                  </label>
                  <span>1회</span>
                </div>
                <div className={styles.formDetail}>30,000 KRW</div>
              </div>

              <div className={styles.classSelectForm}>
                <div className={styles.classSelectCheckBox}>
                  <label className={styles.checkBoxContainer}>
                    <input type="checkbox" {...register("ticket2")} />
                    <span className={styles.checkmark}></span>
                  </label>
                  <span>4회</span>
                </div>
                <div className={styles.formDetail}>120,000 KRW</div>
              </div>
            </div>
          </section>
          <button type="submit">신청하기</button>
        </form>
      </main>
    </div>
  );
};

export default Home;
